### ISSUE TITLE
Order of the tabs should follow the workflow

### ISSUE THREAD

**Issue by owenca** [HaikuArchives/Filer#104]
The positions of Dropzone and Rules tabs should be swapped because the usual workflow is Rules followed by Dropzone and then AutoFiler.

**Comment by owenca** [comment]
Actually, it should Rule, DropZone, AutoFiler, and Help.

**Comment by humdingerb** [comment]
IIRC I put the DropZone first, because once the rules are defined, that's the tab most used if the app is opened at all. But after I introduced saving the state of the active tab, it doesn't matter really anymore.
I don't care much about the order. Maybe going Rules, AutoFiler, DropZone, Help is slightly more logical, as it puts the tabs where the user has to think about creating rules and which folders to monitor first, then the mere using of the app (DropZone), then help.
Anyway, I leave it up to you...

**Comment by owenca** [comment]
The order of the tabs came to my attention only after I noticed that Filer still goes to Dropzone even after creating the default rules, and I must click the Rules tab to see what rules Filer has automatically added. I will change the order then, which will fix this problem too.
