### ISSUE TITLE
Filer, randomly, lose the settings inside the  list"Automatically run Filer on the contents of these folders:"

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/Filer#14]
Is the second time that i notice this behaviour in few days:

Inside Filer, under the "Autofiler" TAB i added five folders to watch with Autofiler, then, suddenly and apparently randomly, I notice that Autofiler doesn't work anymore on certain folders: I noticed, in fact, that if I go in the Autofiler settings, some folder disappears from the list of folders to watch (I refer to the "Automatically run Filer on the contents of these folders:" list.) As I've said, sometime just one folder will disappear from the list and sometime two or more folders disappear.

**Comment by humdingerb** [comment]
Weird. AutoFiler just calls Filer with the files that triggered it. And Filer also shouldn't mess with the AutoFiler settings when it isn't even showing the GUI...   
I haven't seen this yet, but I haven't really used the AutoFiler yet. Do you have more info? Are those disappearing folders on the same partition as the ones surviving? Were those folders deleted and recreated maybe? Was the ~/config/settings/Filer/AutoFilerFolders modified (date)?   
"message ~/config/settings/Filer/AutoFilerFolders" shows if those folders were really removed from the settingsfile.  
I'm a bit at a loss here. If anyone has any info or ideas, please comment.

**Comment by Giova84** [comment]
1: Are those disappearing folders on the same partition as the ones surviving?

Yes: these folders are all on the same partition.

2: Were those folders deleted and recreated maybe?

These folders were definitely disappeared from the list: I have to reinsert  them again, manually, inside Filer's options.

3: ~/config/settings/Filer/AutoFilerFolders file was untouched/unmodified, IIRC. I will investigate further when this issue will occurs again.

**Comment by humdingerb** [comment]
With "2: Were those folders deleted and recreated maybe?" I meant if the folders that were monitored were deleted/recreated, not the entries in the list in the AutoFiler tab. :)

Keep me posted. :)

**Comment by Giova84** [comment]
Ops, sorry: I misunderstood :-)

However those folders weren't deleted nor recreated with Tracker, and I also noticed that inside Filer's options, those entries which disappeared from the list were replaced with a blank/empty line.

**Comment by Giova84** [comment]
Well, I encountered the bug again: I immediately run, from a Terminal window, the command "message /AutoFilerFolders", and here I can see all my five "favourites" folders; however, if I open filer and I look under the Autofiler tab, on five folders I can just see two folders inside Filer's option, the following is a screenshot which shows what I mean:

http://s33.postimg.org/kx4tkfz27/Filer_Trouble.png

I also attempted to restore all Filer's settings file from my Backup, but the issue is still present.

Instead, all Filer's rules are still present/untouched.

**Comment by Giova84** [comment]
I noticed another thing: If i attempt to reinsert lost folders inside Autofiler's option, folders's path will be placed with blank spaces, and the AutoFilerFolders settings file is  reporting "ghost"/unnamed entries:

http://s33.postimg.org/guhz39pvj/Filer_Trouble2.png

To bring the situation in a functionally state, I have to delete the AutoFilerFolders file and insert my favourite folders again.

**Comment by humdingerb** [comment]
This is very strange. Apparently, the AutoFilerFolders settings get overwritten with those refs with an empty path. No idea how refs can lose their path...  
Weirder still, after you replace it with a correct backuped AutoFilerFolders file, you say it still doesn't work and shows those missing items in Filer's AutoFiler tab.

AutoFiler never saves its folder settings, it only loads them. Only Filer saves those folder settings. And only when adding/editing/removing in the AutoFiler tab. Which is never reached when Filer is called from AutoFiler, because it never even displays the GUI...

Not sure this will help in any way, but you could try not autostarting the AutoFiler, but starting it manually from Terminal. At https://www.dropbox.com/s/77gsz0d7s83dfme/Filer_debug1.zip?dl=0 I uploaded a version that'll print out the AutoFiler folder names whenever they're saved. (Which should never happen unless there are changes by the user in the Filer GUI...)

Make sure to temporarily uninstall the "official" filer hpkg by moving it out of /system/packages and you don't have the old AutoFiler still running.

**Comment by Giova84** [comment]
Well, in this month I running your debug version of Filer (and I uninstalled the official hpkg). I made a startup script to automatically start AutoFiler at boot. To log the debug messages, I call AutoFiler in the following way:

AutoFiler > /var/log/Autofiler.log &

Well: the issue which I described, using this debug version, is no longer occurred here. So I tried again with the official version and the bug is occurred again. Very odd. Do you have some idea about? Can I check something else?

**Comment by Giova84** [comment]
As i've said in another ticker, I've built Filer from the last available source; seems to properly works, now.
I will let you know if i will encounter this trouble again.

In the meantime, again, many thanks to you and to all other guys, for the good work!
